### PR TITLE
Building tera_renderer from source

### PR DESCRIPTION
**Pull request by damien-robotsix**
Hi, 

Instead of getting tera_renderer from the release I propose to build it from source.
This allows to compile it for arm (available since pre-release 0.0.35).

Tested on linux/amd64 and linux/arm64. It would be a good idea to check if it works on win/mac.

Have a nice day.

### CODE REVIEW

**Comment by tpoignonec** [comment]
Hi!

Sounds great, thanks!
Did you just try to build or did you run a controller also (just to know if we should test that) ?

**Review by tpoignonec — APPROVED** [review]

**Comment by damien-robotsix** [comment]
Hi, I also run a controller. I did this for a CI of a UAV companion computer.

**Comment by tpoignonec** [comment]
Cool, perfect, I merge this then :)

**Comment by damien-robotsix** [comment]
Thanks

**Pull request merged**
